version: "3"

services:

  # NAT64
  tayga:
    build:
      context: ./tayga
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      SNAT_IPV4: 23.142.232.26
      TAYGA_IPV6: "2602:faf5:64::"
      WAN_INTERFACE: enp1s0
    privileged: true

  # DNS64
  coredns:
    image: coredns/coredns:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
    command: 
      - -conf
      - /etc/coredns/Corefile
